### PR TITLE
Fixed leak in WindowsPowerSource

### LINKED ISSUE #1205: Handle leak in WindowsPowerSource
### First Timers Only

I'm marking this issue for [first-timers-only](https://www.firsttimersonly.com/).  That means that I will only accept a PR for this one from someone who's never contributed to an open source project on GitHub before.

The main goal of this task is to learn the process for submitting a PR -- the GitHub equivalent of writing a "Hello World!" program.  If you already know the PR workflow, please leave this issue for someone else!

Please comment to "claim" this issue if you want to work on it.  If someone else has claimed this (look at "Assignees" to the right) please let them attempt it.

This one is easy (but don't make that statement make you feel bad if you have a hard time with it, there's more to contributing to open source than changing lines of code, especially if it's your first time). I'll hold your hand through this if you need me to. 😄 

### The bug you are fixing

In the `WindowsPowerSource` method `getPowerSource()`, a [handle is created on line 176](https://github.com/oshi/oshi/blob/5b994e4c5650944afb34678fe71ad1e0461f1288/oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsPowerSource.java#L176).  It is intended to be [closed on line 300](https://github.com/oshi/oshi/blob/5b994e4c5650944afb34678fe71ad1e0461f1288/oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsPowerSource.java#L300).  However, [the `break;` statement on line 296](https://github.com/oshi/oshi/blob/5b994e4c5650944afb34678fe71ad1e0461f1288/oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsPowerSource.java#L296) bypasses this closing code.  The code needs to be changed to ensure that handle is closed.

### What to do to fix the bug

1. Define a new `boolean` local variable just before the `for` loop on line 156 to flag whether a battery has been found, initialized to false.
2. In place of the current line 296 `break` statement, toggle the boolean variable to true.
3. Alter the iteration test in the `for` loop at line 156 to also test that the boolean you defined is still false.

### How to submit your change to the repository

Here are the steps to get a PR merged here.
- Read the [CONTRIBUTING](https://github.com/oshi/oshi/blob/master/CONTRIBUTING.md) file for reference.  We'll follow those steps, and I'll walk you through anything you don't understand.
- Fork the project to your own GitHub account, make a local clone, and create a branch for your submission.
- Make the changes described above.
- Commit your changes, push to to your GitHub fork, and create a Pull Request
- Respond to the usually minor comments on code review
- Celebrate! :tada:

### Bonus points

This is a little bit more advanced so don't worry about it if you don't want to.  The identical bug exists on the `4.X` branch.  Commit the same fix there (you might find `git cherry-pick` useful!) and submit a second PR against that branch.

### PR DESCRIPTION
**Pull request by yadunandanbhat**
I've tried to fix #1205 as you've explained.
I have declared a boolean variable before the for loop at line 155 and added an if statement after the for loop, to check if the boolean is still false. And also I've replaced break at 296 with boolean true.
Please check if this is correct.
Thanks.

### CODE REVIEW

File: oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsPowerSource.java [hunk 1]
```diff
@@ -152,8 +152,10 @@ private static WindowsPowerSource getPowerSource(String name) {
         HANDLE hdev = SetupApi.INSTANCE.SetupDiGetClassDevs(GUID_DEVCLASS_BATTERY, null, null,
                 SetupApi.DIGCF_PRESENT | SetupApi.DIGCF_DEVICEINTERFACE);
         if (WinBase.INVALID_HANDLE_VALUE != hdev) {
+        	boolean batteryFound = false;
             // Limit search to 100 batteries max
             for (int idev = 0; idev < 100; idev++) {
+            	if (batteryFound == false) {
```
Comment (dbwiddis) [inline oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsPowerSource.java:158]: This would work, but there are two improvements you can make.
1. Checking that a boolean `==` true or false is easier done just evaluating its value, so `batteryFound` is either true or false by itself.  `!batteryFound` will return true if the value is false, which is what we want to check.
2. You can include this check in the iteration check for the for loop right above it:
`for (int idev = 0; !batteryFound && idev < 100; idev++)`

Comment (yadunandanbhat) [reply oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsPowerSource.java:158]: So it's efficient to remove that 'if' statement wholly and instead incorporate the boolean check in the 'for' loop itself?

Comment (yadunandanbhat) [reply oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsPowerSource.java:158]: Sir, I just did the changes locally and ran the Maven test. It passed. What should I do next? Should I submit another pull request? I haven't worked in this code review environment before, so I don't really know how to proceed.
Thanks.

Comment (dbwiddis) [reply oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsPowerSource.java:158]: Just commit the new change to your local branch and "push" it to your github account. It will automatically update the pull request here.

Comment (dbwiddis) [reply oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsPowerSource.java:158]: As for "efficiency" it's probably not measurable. On the last iteration it would be slightly more efficient to check the "not found" before the iteration limit, but given branch prediction it likely will make zero practical difference.  And the compiler would optimize out the `== false` check as well.   It's more just readability and concise code! :)

Comment (yadunandanbhat) [reply oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsPowerSource.java:158]: Okay sir! I'll do it right now!

**Comment by dbwiddis** [comment]
The code looks great. Just one final change I would ask you to make.  Well, two.

On the line where you define the boolean, you have used a tab character in the indentation.  This produces inconsistent results for different people.  We use a 4-space indentation rather than a tab.  Can you please fix that indentation to use spaces?

Also, if you'd like to give yourself credit in the change log for the fix you are welcome to edit the CHANGELOG.md file as well!  This is a small fix so that's optional, but you are welcome to add it.

**Comment by yadunandanbhat** [comment]
I've fixed the indentation. I didn't insert my name because this was a very small edit :)

**Comment by dbwiddis** [comment]
Perfect! Thanks!
